name: My First GitHub Actions

on: [push]
# Check for elevated permissions
If (-Not ([Security.Principal.WindowsPrincipal]([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "This script requires administrative privileges to modify registry keys."
    Exit 1
}

# Proceed with registry modification
Remove-Item Registry::$_ -Recurse -Force -Verbose
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
